server:
  port: 8081

spring:
  application:
    name: service1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: host.docker.internal
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

    metadata-map:
      management.port: ${management.server.port}
      management.context-path: /actuator

management:
  server:
    port: 18081
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
