global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-cloud"
    metrics_path: "/actuator/prometheus"

    eureka_sd_configs:
      - server: "http://host.docker.internal:8761/eureka"
        refresh_interval: 30s

    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application

      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance

      # Eureka 메타데이터에 넣어둔 management.port를 사용해서
      # 실제 접근 주소(__address__ = host:port)를 재구성
      - source_labels:
          [
            __meta_eureka_app_instance_hostname,
            __meta_eureka_app_instance_metadata_management_port,
          ]
        regex: "(.+);(.+)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace
